name: CI                          # nazwa pipeline widoczna na GitHubie

on:
  push:
    branches: [main]              # odpala się przy każdym pushu na main
  pull_request:
    branches: [main]              # i przy każdym Pull Request do main

jobs:
  build-dotnet:                   # JOB 1 — backend
    runs-on: ubuntu-latest        # odpala się na maszynie z Ubuntu
    steps:
      - uses: actions/checkout@v4           # pobiera kod z repo
      - uses: actions/setup-dotnet@v4       # instaluje .NET 10
        with:
          dotnet-version: '10.0.x'
      - name: Restore                       # pobiera NuGet packages
        run: dotnet restore
      - name: Build                         # kompiluje projekt
        run: dotnet build --no-restore
      - name: Test                          # odpala testy
        run: dotnet test --no-build

  build-frontend:                 # JOB 2 — frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4           # pobiera kod
      - uses: actions/setup-node@v4         # instaluje Node.js 20
        with:
          node-version: '25'
      - name: Install                       # npm install
        run: npm install --legacy-peer-deps

      - name: Install web deps
        working-directory: apps/web
        run: rm -rf node_modules package-lock.json && npm install
        
      - name: Build                         # npm run build
        run: npm run build